# Generated by Django 3.0.7 on 2020-06-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servidores',
            new_name='adminServidores',
        ),
    ]
